export const autConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCES: "LOGIN_SUCCES",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  SIGNUP_SETBOOLEAN: "SIGNUP_SETBOOLEAN",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  GETT_ALL_USERS_SUCESS:"GETT_ALL_USERS_SUCESS"
};
export const userConstants = {
  GET_USER_ADDRESS_REQUEST: "GET_USER_ADDRESS_REQUEST",
  GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS",
  GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",
  ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
  ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
  ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",
  ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
  ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
  ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",

  GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
  GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
  GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",

  GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
  GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
  GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",
};
export const categoryConstans = {
  GETT_ALL_CATEGORIES_REQUEST: "GETT_ALL_CATEGORIES_REQUEST",
  GETT_ALL_CATEGORIES_SUCCES: "GETT_ALL_CATEGORIES_SUCCES",
  GETT_ALL_CATEGORIES_FAILURE: "GETT_ALL_CATEGORIES_FAILURE",
 };
 export const productConstans = {
  GETT_PRODUCTS_BY_SLUG: "GETT_PRODUCTS_BY_SLUG",
  GET_PRODUCT_PAGE_REQUEST:'GET_PRODUCT_PAGE_REQUEST',
  GET_PRODUCT_PAGE_SUCCES:'GET_PRODUCT_PAGE_SUCCES',
  GET_PRODUCT_PAGE_FAILURE:'GET_PRODUCT_PAGE_FAILURE',
  GETT_PRODUCT_DETAILS_BY_ID_REQUEST:'GETT_PRODUCT_DETAILS_BY_ID_REQUEST',
  GETT_PRODUCT_DETAILS_BY_ID_SUCCES:'GETT_PRODUCT_DETAILS_BY_ID_SUCCES',
  GETT_PRODUCT_DETAILS_BY_ID_FAILURE:'GETT_PRODUCT_DETAILS_BY_ID_FAILURE',
  ADD_COMENT_REQUEST:"ADD_COMENT_REQUEST",
  ADD_COMENT_SUCCESS:"ADD_COMENT_SUCCESS",
  ADD_COMENT_FAILURE:"ADD_COMENT_FAILURE",
  GETT_ALL_PRODUCTS: "GETT_ALL_PRODUCTS",
};
export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  RESET_CART: "RESET_CART",
  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
};
export const chatroomConstans = {
  GETT_ALL_CHATROOMS_REQUEST: "GETT_ALL_CHATROOMS_REQUEST",
  GETT_ALL_CHATROOMS_SUCCES: "GETT_ALL_CHATROOMS_SUCCES",
  GETT_ALL_CHATROOMS_FAILURE: "GETT_ALL_CHATROOMS_FAILURE",
 };